2023-01-27 11:32:24,365 INFO    MainThread:2608 [wandb_setup.py:_flush():68] Configure stats pid to 2608
2023-01-27 11:32:24,367 INFO    MainThread:2608 [wandb_setup.py:_flush():68] Loading settings from C:\Users\au475271\.config\wandb\settings
2023-01-27 11:32:24,367 INFO    MainThread:2608 [wandb_setup.py:_flush():68] Loading settings from C:\Users\au475271\Desktop\fedasync-with-fairness\wandb\settings
2023-01-27 11:32:24,367 INFO    MainThread:2608 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2023-01-27 11:32:24,367 INFO    MainThread:2608 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'src\\main.py', 'program': 'c:\\Users\\au475271\\Desktop\\fedasync-with-fairness\\src\\main.py'}
2023-01-27 11:32:24,368 INFO    MainThread:2608 [wandb_init.py:_log_setup():478] Logging user logs to C:\Users\au475271\Desktop\fedasync-with-fairness\wandb\run-20230127_113224-6vzp7bng\logs\debug.log
2023-01-27 11:32:24,368 INFO    MainThread:2608 [wandb_init.py:_log_setup():479] Logging internal logs to C:\Users\au475271\Desktop\fedasync-with-fairness\wandb\run-20230127_113224-6vzp7bng\logs\debug-internal.log
2023-01-27 11:32:24,368 INFO    MainThread:2608 [wandb_init.py:init():518] calling init triggers
2023-01-27 11:32:24,369 INFO    MainThread:2608 [wandb_init.py:init():521] wandb.init called with sweep_config: {}
config: {}
2023-01-27 11:32:24,369 INFO    MainThread:2608 [wandb_init.py:init():571] starting backend
2023-01-27 11:32:24,369 INFO    MainThread:2608 [wandb_init.py:init():575] setting up manager
2023-01-27 11:32:24,395 INFO    MainThread:2608 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-01-27 11:32:24,443 INFO    MainThread:2608 [wandb_init.py:init():582] backend started and connected
2023-01-27 11:32:24,465 INFO    MainThread:2608 [wandb_init.py:init():670] updated telemetry
2023-01-27 11:32:24,589 INFO    MainThread:2608 [wandb_init.py:init():710] communicating run to backend with 60.0 second timeout
2023-01-27 11:32:27,801 WARNING MsgRouterThr:2608 [router.py:message_loop():77] message_loop has been closed
2023-01-27 11:32:29,655 ERROR   MainThread:2608 [wandb_init.py:init():1135] error
Traceback (most recent call last):
  File "C:\Users\au475271\Miniconda3\envs\py38-fedasync\lib\site-packages\wandb\sdk\wandb_init.py", line 1108, in init
    run = wi.init()
  File "C:\Users\au475271\Miniconda3\envs\py38-fedasync\lib\site-packages\wandb\sdk\wandb_init.py", line 713, in init
    result = run_init_handle.wait(
  File "C:\Users\au475271\Miniconda3\envs\py38-fedasync\lib\site-packages\wandb\sdk\lib\mailbox.py", line 271, in wait
    raise MailboxError("transport failed")
wandb.errors.MailboxError: transport failed
